### ISSUE TITLE
The Maven repo is down

### ISSUE THREAD

**Issue by jaytaylor** [snowplow/scala-maxmind-iplookups#13]
http://maven.snplow.com/releases/ is not working, what's up with that?

**Comment by nhthai2207** [comment]
I have same issue when build project: https://github.com/ornicar/lila
[warn] 	:: com.github.ornicar#scalalib_2.11;5.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving com.github.ornicar#scalalib_2.11;5.2 ...

Is it the same root issues?
Thanks!

**Comment by alexanderdean** [comment]
@nhthai2207 please file an issue on ornicar's project, not this one.

**Comment by nhthai2207** [comment]
Thanks you!
