### ISSUE TITLE
Lookup timeout config

### ISSUE THREAD

**Issue by alonpeer** [snowplow/scala-maxmind-iplookups#27]
It seems that there's a hard-coded 4 seconds timeout on lookups in `performLookupsWithoutLruCache()`. This can cause possible I/O bottlenecks and should be at least configurable in the `IpLookups` class.

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by BenFradet** [comment]
The timeout doesn't exist anymore because of #44, closing
