### ISSUE TITLE
Update to GeoLite2

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/scala-maxmind-iplookups#31]
For some IP's (e.g. in São Paulo, Brazil), MaxMind's GeoLite correctly identifies the lat/lon coordinates, but fails to provide the city name. I've run some tests with GeoLite2 and that problem seems to be solved.

There is a Scala wrapper based on Snowplow's implementation at https://github.com/Sanoma-CDA/maxmind-geoip2-scala. Implementation seems pretty straightforward - do you see any downsides of updating to GeoLite2?

Update: running the following query returns 95% of results from São Paulo's coordinates - but city name is null

`SELECT geo_latitude, geo_longitude, count(*) FROM atomic.events
WHERE geo_city IS NULL
GROUP BY 1,2
ORDER BY 3 DESC`

**Comment by alexanderdean** [comment]
Hi @bernardosrulzon - thanks for the suggestion! Is there any reason why we couldn't support both the legacy and the new databases alongside each other? If not - PR welcome!

**Comment by BenFradet** [comment]
taken care of in #35
