### ISSUE TITLE
Update README as per v0.3.0

### ISSUE THREAD

**Issue by anand-singh** [snowplow/scala-maxmind-iplookups#32]
Scala MaxMind IP Lookups v0.3.0

Improved thread safety : **Thread safety**

Switched from LruMap to SynchronizedLruMap (#28)

**Build:** Added dedicated Vagrant setup (#30)

**Comment by mslinn** [comment]
Is this project dead?

**Comment by alexanderdean** [comment]
No

**Comment by mslinn** [comment]
Good to hear this project still has a future. It seems useful. This issue, and the others still open, have not been addressed in quite a while. I see https://github.com/ListnPlay/maxmind-geoip2-scala has a few fixes. Any plans for updating this project in the near future?

**Comment by alexanderdean** [comment]
Hi Mike - we don't have a release of this project on the Trello board for the near future.

**Comment by csaltos** [comment]
We are using scala-maxmind-iplookups at production at Talenteca.com and it's working great. Long live to scala-maxmind-iplookups project.

**Comment by alexanderdean** [comment]
Woot! Thanks for the kind words @csaltos

**Comment by BenFradet** [comment]
Not sure what the point of this issue was closing
