### ISSUE TITLE
Add Maxmind discontinuation notice to the README

### ISSUE THREAD

**Issue by miike** [snowplow/scala-maxmind-iplookups#36]
> We will be discontinuing updates to the GeoLite Legacy databases as of April 1, 2018. You will still be able to download the April 2018 release until January 2, 2019. GeoLite Legacy users will need to update their integrations in order to switch to the free GeoLite2 or commercial GeoIP databases by April 2018.

Full notice is [here](https://dev.maxmind.com/geoip/geoip2/geolite2/) and blog post [here](https://blog.maxmind.com/2018/01/02/discontinuation-of-the-geolite-legacy-databases/) - it looks like this will primarily impact those using .dat files.

**Comment by BenFradet** [comment]
the library has been updated to geolite2 in #35 if I'm not mistaken

**Comment by miike** [comment]
Yes! More a note of should we include warnings/have a deprecation schedule for anyone using the legacy files?

**Comment by BenFradet** [comment]
Do you mean for the library itself or through an enrich job?

**Comment by miike** [comment]
Perhaps both so that Snowplow users and those who use the library independently of enrich know about it?

**Comment by BenFradet** [comment]
Good point we could create a discourse post discussing it for Snowplow users and add a warning in the readme for people using previous versions.

**Comment by alexanderdean** [comment]
Done @BenFradet - https://github.com/snowplow/snowplow/milestone/156

Please make any edits.
