### ISSUE TITLE
Remove dependency resolvers

### ISSUE THREAD

**Issue by dyf102** [snowplow/scala-maxmind-iplookups#37]
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#util-collection;5.3.10: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter:util-collection:5.3.10 (/code_disk/scala-maxmind-iplookups/project/ScalaMaxmindIpLookupsBuild.scala#L30)
[warn] 		  +- com.snowplowanalytics:scala-maxmind-iplookups_2.9.3:0.3.0
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter#util-collection;5.3.10: not found
[error] Total time: 14 s, completed Jan 25, 2018 3:09:57 PM

**Comment by BenFradet** [comment]
Hey @dyf102 it seems twitter moved its maven repo to https that's why you're getting this error as the sbt version we're using is unable to resolve redirects

**Comment by BenFradet** [comment]
We're now using a version which is on central so no need for a resolver, changing the ticket name
