### ISSUE TITLE
Move away from Twitter's util-collection

### ISSUE THREAD

**Issue by BenFradet** [snowplow/scala-maxmind-iplookups#42]
Ticket name will need to be to refined when we find a good replacement

**Comment by three** [comment]
I researched a few alternatives to `SynchronizedLruMap` which requires util-collection. There's `LRUMap` from Apache Commons but that might not help if we're trying to avoid adding libraries. Scala's standard library has `LinkedHashMap` which keeps track of the order things were added, but with some extra logic can be made into an LRU cache. The `LinkedHashMap` would need to be synchronized manually.

Let me know what you think.

cc @BenFradet

**Comment by BenFradet** [comment]
cool thanks, however I'm not against adding a library, I'd just like to move away from the twitter's ecosystem.

**Comment by BenFradet** [comment]
btw https://github.com/cb372/scalacache offers cats-effect integration with quite a few cache libraries, it might be worth investigating if one could satisfy our needs.

Maybe @chuwy has some xp with the lib?

**Comment by chuwy** [comment]
No, I have not unfortunately. However, from what I can see scalacache doesn't provide any in-memory cache structures. So, if we're not planning to use persistent caches on EMR (did we ever consider that?) I think it would be better just to implement/borrow `SynchronizedLruMap`. In that case we need to pay double attention to not expose any non referentially transparent API, e.g. only:

```scala
object LRUMap {
    def create[F[_]: Sync, K, V](size: Int): F[LRUMap[K, V]] = ???
    def put[F[_]: Sync, K, V](lruMap: LRUMap[K, V]): F[Unit] = ???
    def get[F[_]: Sync, K, V](lruMap: LRUMap[K, V], key: K): F[Option[V]] = ???
}
```

This also will greatly help with synchronization.

**Comment by ben-manes** [comment]
`ScalaCache` is remote-oriented, with local providers. This can be a negative for local-only usages since it uses String keys and implements its own version expiration & memoization on top of the underlying cache. I think its best fit is when you use a remote cache in production and want a local cache for test or developer environments.

[Scaffeine](https://github.com/blemale/scaffeine) is another option as it provides an Scala shim to `Caffeine` to make it feel more idiomatic.

**Comment by chuwy** [comment]
> guava and caffeine are in memory unless I'm mistaken

Yep, you're right! Though both are quite heavy dependencies, not a big win over `util-collection`.

> I don't see that as an option since only one enrichment platform runs on emr

I'm not sure what do you mean by platform. But I agree that for EMR it would be probably less useful than for RT, e.g. double-level cache: first try to get it from in-memory LRU, then from DynamoDB/Redis, then from actual service.

**Comment by BenFradet** [comment]
ah you meant persistent caches in general, yes that's definitely further out than this issue.

>Yep, you're right! Though both are quite heavy dependencies, not a big win over util-collection.

yes, maybe guava is a bad idea given it has led to conflicts before.
