### ISSUE TITLE
Remove useless Future

### ISSUE THREAD

**Issue by BenFradet** [snowplow/scala-maxmind-iplookups#44]
Futures are created and a blocking call is made directly effectively making them useless:

https://github.com/snowplow/scala-maxmind-iplookups/blob/d8ccda56a32eeeec1e6a9f32ec94540c4ad059c4/src/main/scala/com.snowplowanalytics.maxmind/iplookups/IpLookups.scala#L167-L169

**Comment by alexanderdean** [comment]
Which is the blocking call?

**Comment by BenFradet** [comment]
Futures are built to be immediately awaited (`Await` is blocking) which render them effectively useless.
