### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow/scala-maxmind-iplookups#51]
- BINTRAY_SNOWPLOW_MAVEN_USER
- BINTRAY_SNOWPLOW_MAVEN_API_KEY

Additionally, there is no scala-maxmind-iplookups repo in snowplow-maven so that needs to be created.
Also, mirroring to central will need to be enabled.

- [x] AD: add creds
- [x] AD: create repo in Bintray
- [x] BF: push first M1
- [x] AD: add to JCenter
- [x] AD: activate Maven Central sync

**Comment by alexanderdean** [comment]
Over to you @BenFradet for step 3. By the way, when I do step 4, should I check:

[ ]  Host my snapshot build artifacts on the OSS Artifactory at https://oss.jfrog.org

This allows you to have your project’s builds snapshots deployed to https://oss.jfrog.org and to release and publish them to Bintray in one click.

**Comment by alexanderdean** [comment]
Link is https://bintray.com/snowplow/snowplow-maven/scala-maxmind-iplookups

**Comment by BenFradet** [comment]
it's failing but I suspect it comes from bintray since I can't access https://bintray.com/snowplow/snowplow-maven

**Comment by BenFradet** [comment]
forgot about #54 my bad

**Comment by alexanderdean** [comment]
JCenter link is not working, have sent another support ticket to Bintray.

**Comment by alexanderdean** [comment]
JCenter link working now, submitted. Can't remember how long we have to wait before we can hit the Maven Central button.

**Comment by BenFradet** [comment]
ok, keep me posted :+1:

**Comment by alexanderdean** [comment]
I believe the artifact is on Maven Central now, please confirm!

**Comment by BenFradet** [comment]
yup! thanks, I'll release 0.4.0 momentarily
