### ISSUE TITLE
Add readme examples

### ISSUE THREAD

**Issue by vartikajain** [snowplow/scala-maxmind-iplookups#79]
ipLookups.performLookups("213.52.50.8").ipLocation match {
      case Right(loc) =>
        println(loc.countryCode)   // => "NO"
        println(loc.countryName)   // => "Norway"
      case Left(f) =>
        println(f)
    } 
Doesnt work.
Getting following error at Line 2 and 5
Constructor cannot be instantiated to expected type, found Right[A,B] , required Option[Validation[Throwable, model.IpLocation]]

**Comment by BenFradet** [comment]
Yes we're redesigning the API, the current readme is for the upcoming 0.5.0

**Comment by vartikajain** [comment]
Thank you. This might be too much to ask but will you guys be including more examples. I tried searching on net for usages of api but couldn't find many.

**Comment by BenFradet** [comment]
yup 👍 cc @three

**Comment by saj1th** [comment]
By more examples, do we mean examples for ISP, ConnectionType data ? For IP lookups, the test cases seem to be providing good examples

**Comment by BenFradet** [comment]
yes I think we want to make the readme more extensive (ISP, domain, connection type) :+1:

**Comment by saj1th** [comment]
Not sure would be able to test without the files. Only got the IP db.  Sorry about that
