### ISSUE TITLE
fix test "providing an invalid ip should fail" located in IpLookupsTest.scala

### ISSUE THREAD

**Issue by dorsev** [snowplow/scala-maxmind-iplookups#96]
**Library version**:
I checked out develop(version := "0.5.0") and ran sbt clean compile test and got the following error

  | field           | expected                                                                  | actual                                                                                       |                                                                                                            
x | iplocation      | Some(Left(java.net.UnknownHostException: not: Name or service not known)) | Some(Left(java.net.UnknownHostException: not: nodename nor servname provided, or not known)) | Some(Left(not: Name or service not known)) != Some(Left(not: nodename nor servname provided, or not known))
x | isp             | Some(Left(java.net.UnknownHostException: not: Name or service not known)) | Some(Left(java.net.UnknownHostException: not: nodename nor servname provided, or not known)) | Some(Left(not: Name or service not known)) != Some(Left(not: nodename nor servname provided, or not known))
x | organization    | Some(Left(java.net.UnknownHostException: not: Name or service not known)) | Some(Left(java.net.UnknownHostException: not: nodename nor servname provided, or not known)) | Some(Left(not: Name or service not known)) != Some(Left(not: nodename nor servname provided, or not known))
x | domain          | Some(Left(java.net.UnknownHostException: not: Name or service not known)) | Some(Left(java.net.UnknownHostException: not: nodename nor servname provided, or not known)) | Some(Left(not: Name or service not known)) != Some(Left(not: nodename nor servname provided, or not known))
x | connection type | Some(Left(java.net.UnknownHostException: not: Name or service not known)) | Some(Left(java.net.UnknownHostException: not: nodename nor servname provided, or not known)) | Some(Left(not: Name or service not known)) != Some(Left(not: nodename nor servname provided, or not known))
Expected :Some(Left(not: nodename nor servname provided, or not known))
Actual   :Some(Left(not: Name or service not known))
**Expected behavior**:
test should pass
**Actual behavior**:
test fails with the above msg
**Steps to reproduce**:
run sbt clean compile test

btw:
I am building this code on a mac machine.. Am I the only one seeing this ?

**Comment by BenFradet** [comment]
ah yes, those are os-specific :+1:

**Comment by dorsev** [comment]
ok
