### ISSUE TITLE
Remove thread safety warning regarding LRU cache from readme file

### ISSUE THREAD

**Issue by nitayk** [snowplow/scala-maxmind-iplookups#99]
Hey,
So in the readme file, you can find:

"LRU cache
We recommend trying different LRU cache sizes to see what works best for you.

Please note that the LRU cache is not thread-safe (see this note). Switch it off if you are thinking about performing ip lookups with the same IpLookups instance across threads."

While in the releases section, under `Scala MaxMind IP Lookups v0.3.0` you can find:
"Thread safety
Switched from LruMap to SynchronizedLruMap (#28)"

I think it needs clarification

**Comment by BenFradet** [comment]
ah yes this is an artifact of the previous versions, it's now thread-safe, feel free to open a PR :+1:
